env:
  # Values for namespace
  namespace: "test"
  # Values for application
  repository:  "us-central1-docker.pkg.dev/fast-ability-382900/artemis/artemis"
  tag: "2.0.0"
  port: "5000"
  domain: "domainaws.com"
  environment: "dev"
  app_name: "artemis"

# # Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      
      - name: Clone a repo
        run: |
          git clone "${{ env.repo }}"


      - name: Checkout branch
        working-directory: ${{ env.app_name }}
        run: |
          git checkout "${{ env.app_version }}"


      - name: Build Image
        working-directory: ${{ env.app_name }}
        run: |
          docker build  -t  ${{ env.repo_region }}-docker.pkg.dev/${{ env.project_id }}/${{ env.app_name }}/${{ env.app_name }}:${{ env.tag_new_version }}  . 


      # Authenticate to GCP
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT }}'


      - name: Authenticate to repository
        run: |
          gcloud auth configure-docker  ${{ env.repo_region }}-docker.pkg.dev
          
          

      - name: Docker push
        working-directory: ${{ env.app_name }}
        run: |
          docker push  ${{ env.repo_region }}-docker.pkg.dev/${{ env.project_id }}/${{ env.app_name }}/${{ env.app_name }}:${{ env.tag_new_version }}  
     